version: "3"

services:
  sample-sso:
    image: sample-keycloak
    container_name: sample-sso
    networks:
      sample:
        aliases:
          - sso.sample-fb.zzzzzzzz.internal
    ports: 
      - 8080:8080
      - 8787:8787
    restart: always
    extra_hosts:
      - "keycloakdb.sample-fb.zzzzzzzz.internal:192.168.65.2"
    
  sample-app:
    image: sample-httpd-oidc
    container_name: sample-app
    networks:
      - sample
#    ports:
#      - 80:80
    restart: always
    depends_on:
      - sample-sso
  sample-lb:
    image: sample-lb-dev
    container_name: sample-lb-dev
    networks:
      - sample
    ports:
      - 80:80
    restart: always
    depends_on:
      - sample-sso
      - sample-app

networks:
  sample:
  