version: "3"

services:
  sample-sso1:
    image: sample-keycloak
    container_name: sample-sso1
    networks:
      sample:
        aliases:
          - sso.sample-fb.zzzzzzzz.internal
    ports: 
      - 18080:8080
      - 18787:8787
      - 17800:7800
    restart: always
    extra_hosts:
      - "keycloakdb.sample-fb.zzzzzzzz.internal:192.168.65.2"
      - "sso.sample-fb.zzzzzzzz.internal:192.168.65.2"
    
  sample-sso2:
    image: sample-keycloak
    container_name: sample-sso2
    networks:
      sample:
        aliases:
          - sso.sample-fb.zzzzzzzz.internal
    ports: 
      - 28080:8080
      - 28787:8787
      - 27800:7800
    restart: always
    extra_hosts:
      - "keycloakdb.sample-fb.zzzzzzzz.internal:192.168.65.2"
      - "sso.sample-fb.zzzzzzzz.internal:192.168.65.2"

  sample-app:
    image: sample-httpd-oidc
    container_name: sample-app
    networks:
      - sample
#    ports:
#      - 80:80
    restart: always
    depends_on:
      - sample-sso1
      - sample-sso2

  sample-lb:
    image: sample-lb-dev
    container_name: sample-lb-dev
    networks:
      - sample
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - sample-sso1
      - sample-sso2
      - sample-app

networks:
  sample:
  